### ISSUE TITLE
SciView: NoSuchMethodError

### ISSUE THREAD

**Issue by tferr** [fiji/Simple_Neurite_Tracer#65]
@kephale, Subscribers to the NeuroAnatomy & SciView update sites get this:
```
Exception in thread "Thread-12" java.lang.NoSuchMethodError: sc.iview.SciView.addWindowListener(Ljava/awt/event/WindowListener;)V
	at sc.fiji.snt.SciViewSNT.setSciView(SciViewSNT.java:135)
	at sc.fiji.snt.SciViewSNT.initSciView(SciViewSNT.java:110)
	at sc.fiji.snt.SciViewSNT.<init>(SciViewSNT.java:103)
	at sc.fiji.snt.SNTUI.lambda$32(SNTUI.java:1598)
	at java.lang.Thread.run(Thread.java:748)
```
This is because the SciView version shipped is older than SciView 7b5befb. Shall SciView be updated on its updateSite, or shall I start uploading the updated jar to NeuroAnatomy?

**Comment by kephale** [comment]
It should be updated soon. I just keep forgetting to do tests on my apple laptop in the evening :X

**Comment by kephale** [comment]
I'm aiming for Saturday/Sunday to push a new release to the update site
